// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entities "github.com/alvinpiter/cp-helper/entities"
	mock "github.com/stretchr/testify/mock"
)

// CodeforcesRepository is an autogenerated mock type for the CodeforcesRepository type
type CodeforcesRepository struct {
	mock.Mock
}

// GetProblems provides a mock function with given fields:
func (_m *CodeforcesRepository) GetProblems() ([]*entities.CodeforcesProblem, error) {
	ret := _m.Called()

	var r0 []*entities.CodeforcesProblem
	if rf, ok := ret.Get(0).(func() []*entities.CodeforcesProblem); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.CodeforcesProblem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubmissions provides a mock function with given fields: _a0
func (_m *CodeforcesRepository) GetSubmissions(_a0 string) ([]*entities.CodeforcesSubmission, error) {
	ret := _m.Called(_a0)

	var r0 []*entities.CodeforcesSubmission
	if rf, ok := ret.Get(0).(func(string) []*entities.CodeforcesSubmission); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.CodeforcesSubmission)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
