// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entities "github.com/alvinpiter/cp-helper/entities"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CompareWithFilter provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *Service) CompareWithFilter(_a0 string, _a1 string, _a2 string, _a3 *entities.FilterParameter) ([]entities.Problem, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 []entities.Problem
	if rf, ok := ret.Get(0).(func(string, string, string, *entities.FilterParameter) []entities.Problem); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Problem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, *entities.FilterParameter) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
